services:
  - type: web
    name: kicktracker
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --workers 3 --threads 2 --timeout 60 --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: SECRET_KEY
        generateValue: true
